### PR TITLE
fix: fix race condition for connections that spam packets during startup

### LINKED ISSUE #1200: [Bug]: Since Agent 1.46.4 - SSH Proxy connection fail
### Bug Description

I'm using the latest version of hoop server (1.46.11) and update the agent on a remote server from (1.46.3) to (1.46.4).

Since the Agent update, I can't establish SSH proxy, downgrading the agent again to (1.46.3) works as workaround.

I already tested the latest version of the agent too (1.46.10) and I still face the issue.

### Steps to Reproduce

- Install Agent >= 1.46.4 on a remote host with private key and connecting to itself (localhost)
- Using hoopcli on Mac/Linux/Windows with connect will not work.

### Expected Behavior

(With 1.46.3)

INFO ssh 🔒: proxy started, ready to accept connections at 127.0.0.1:2223
INFO ssh 🔒: /usr/bin/ssh 127.0.0.1 -p 2223 -o StrictHostKeyChecking=no

Last login: Wed Dec 17 16:26:44 2025 from 127.0.0.1
user@server:~$ 

### Actual Behavior

(With >= 1.46.4)

INFO ssh 🔒: proxy started, ready to accept connections at 127.0.0.1:2223
INFO ssh 🔒: /usr/bin/ssh 127.0.0.1 -p 2223 -o StrictHostKeyChecking=no

### Version

1.46.4

### Browser(s)

Firefox

### Operating System

Windows 11

### Screenshots

_No response_

### Additional Context

_No response_

### Relevant Log Output

```shell
Log from the agent on the remote server with (1.46.4)

{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"controller/agent.go:189","msg":"received connect request","sid":"XXXXXX-XXXX-XXXX"}
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"controller/agent.go:250","msg":"sent gateway connect ok","sid":"XXXXXX-XXXX-XXXX"}
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"controller/ssh.go:49","msg":"starting SSH proxy connection at 127.0.0.1:22","sid":"XXXXXX-XXXX-XXXX","conn":"1"}
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"controller/ssh.go:49","msg":"starting SSH proxy connection at 127.0.0.1:22","sid":"XXXXXX-XXXX-XXXX","conn":"1"}]
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:76","msg":"establishing new SSH connection with server 127.0.0.1:22","conn":"1","sid":"XXXXXX-XXXX-XXXX"}
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:76","msg":"establishing new SSH connection with server 127.0.0.1:22","conn":"1","sid":"XXXXXX-XXXX-XXXX"}]
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:205","msg":"request type:\"pty-req\", wantreply:true, payload-length=294","conn":"1","ch":1}
{"level":"warn","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:211","msg":"unable to obtain channel","conn":"1","ch":1}
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:205","msg":"request type:\"shell\", wantreply:true, payload-length=0","conn":"1","ch":1}
{"level":"warn","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:211","msg":"unable to obtain channel","conn":"1","ch":1}
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:180","msg":"opening channel type=session, id=1, extra-data-length=0","conn":"1","ch":1}
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:205","msg":"request type:\"env\", wantreply:false, payload-length=21","conn":"1","ch":1}
{"level":"warn","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:211","msg":"unable to obtain channel","conn":"1","ch":1}
{"level":"info","timestamp":"2025-12-17T16:36:25Z","logger":"ssh/proxy.go:189","msg":"channel opened type=session, id=1, extra-data-length=0","conn":"1","ch":1}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by racerxdl**
## 📝 Description

There was an race condition setting up the memory state for the agent connections. This would only happen if the client sent two following packets causing them to both trigger a new connection.

This fix adds a _per SID_ sync mutex which wouldn't interfere in parallel connections but will ensure the packet flow goes correctly sequential in processor.

## 🔗 Related Issue

Fixes #1200
Fixes ENG-189

## 🚀 Type of Change

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update
- [ ] 🎨 Style/UI update
- [ ] ♻️ Code refactor
- [ ] ⚡ Performance improvement
- [ ] ✅ Test update
- [ ] 🔧 Build configuration change
- [ ] 🧹 Chore

## 🧪 Testing

The problem specifically was described at #1200  - I couldn't reproduce locally with the versions described in the ticket but was possible to reproduce the exact issue with SSH client in 10+ version (server version does not matter).

Easy to reproduce using nixpkgs since it has upstream OpenSSH Client:

```bash
nix-shell -p openssh --run "ssh hoop@localhost -p 2233"
```

### CODE REVIEW

File: agent/controller/agent.go [hunk 1]
```diff
@@ -122,8 +126,24 @@ func (a *Agent) Close(cause error) {
...
+func (a *Agent) getOrAddConnMutex(connId string) *sync.Mutex {
+	a.connMtxStoreMtx.Lock()
+	defer a.connMtxStoreMtx.Unlock()
+
+	if _, ok := a.connMtx[connId]; !ok {
+		a.connMtx[connId] = &sync.Mutex{}
+	}
+	return a.connMtx[connId]
+}
+
```
Comment (matheusfrancisco) [inline agent/controller/agent.go]: change connId for sid.

File: agent/controller/agent.go [hunk 2]
```diff
@@ -203,7 +223,7 @@ func (a *Agent) Run() error {
 		}
 
 		// We don't need to wait here for the result, so we just spawn a goroutine to process it.
-		go a.processPacket(pkt)
+		a.processPacket(pkt)
```
Comment (matheusfrancisco) [inline agent/controller/agent.go]: Looks like you removed the go by mistake, right it? 
if you have two sid -> 1 and sid -> 2

1. The Run() loop calls a.client.Recv() to get a packet
2. It calls processPacket(pkt) synchronously (blocking the loop)
3. While processPacket is executing for sid 1, the entire Run() loop is blocked
4. Packets for sid 2 can't even be received/processed because the loop is stuck

sid 1 running a long operation WILL block sid 2 - not because of the per-sid mutex, but because the main receive loop is single-threaded and synchronous.

File: agent/controller/agent.go [hunk 3]
```diff
@@ -122,8 +126,24 @@ func (a *Agent) Close(cause error) {
...
+}
+
 func (a *Agent) processPacket(pkt *pb.Packet) {
 	sid := string(pkt.Spec[pb.SpecGatewaySessionID])
+
+	// Make it pipelined for each connection but parallel between connections
+	mtx := a.getOrAddConnMutex(sid)
+	mtx.Lock()
+	defer mtx.Unlock()
+
```
Comment (matheusfrancisco) [inline agent/controller/agent.go:148]: Also, the http proxy handles sid and conid internally. Sid can have many .
```
HTTP Request 1 (sid=abc, connID=1) → acquires mutex for "abc"
HTTP Request 2 (sid=abc, connID=2) → BLOCKED waiting for mutex "abc"
HTTP Request 3 (sid=abc, connID=3) → BLOCKED waiting for mutex "abc"conid

```
this will make the proxy  really slow for freelens and broswer  that uses websocket

Comment (matheusfrancisco) [reply agent/controller/agent.go:148]: and we kind same some timeouts on http proxy for request.

File: agent/controller/agent.go (hunk 2 above)
Comment (racerxdl) [reply agent/controller/agent.go]: Yep I removed by mistake.

About the flow, The run loop wont be blocked (it was inteded to have the `go` there. I will update.

**Comment by sandromello** [comment]
✅ Build Completed with Success, Version=1222.0.0-665e620

**Comment by sandromello** [comment]
✅ Build Completed with Success, Version=1222.0.0-22e81af

**Comment by sandromello** [comment]
✅ Build Completed with Success, Version=1222.0.0-989e1be
